sample_prompt = [
    [
        '- Image 1.1: Generate an image that \n'
        '    - Description: A dreamy scene of a young couple meeting for the first time in a picturesque garden. '
        'The girl is wearing a light summer dress, and the boy is in casual attire. They are surrounded by '
        'blooming flowers and lush greenery under a clear blue sky.\n'
        '    - Base Style Settings: artStyles: Romanticism, Impressionism, Fantasy, artMedium - Drawing: '
        'Illustration, Hand-Drawn, artMedium - Paint: Watercolor, artMedium - Text: Calligraphy, Camera - '
        'Scenes: Cinematic, Golden Hour, Filmic, Camera - Film Types: 35mm, Polaroid, Vintage, Camera - Lenses '
        'and Perspective: Wide Angle, Closeup, First-Person view, Camera - Blur and Distortion: Blur Effect, '
        'Camera - Camera Settings: Soft Focus, Shutter Speed 1/1000, Color - Chromatic Palettes: Warm Color '
        'Palette, Light Blue Background, Light, Color - Contrast: High Contrast, Dimensionality - 2D-5D: 2D, '
        '2.5D, Intangibles - Emotions and Qualities: Happy, Nostalgic, Romantic, Lighting - Types: Natural '
        'Lighting, Sunlight, Rays of Shimmering Light, Lighting - Styles: Soft Lighting, Beautiful Lighting, '
        'Material - Opacity: Translucent, Material - Reflection and Refraction: Glossy, Material - Color: '
        'Iridescent\n'
        '    - Elements: blooming flowers, lush greenery, clear blue sky, young couple, light summer dress, '
        'casual attire',
        '- Image 1.2: Generate an image that \n'
        '    - Description: A close-up view of the girl closing her eyes, with a soft, nostalgic expression on '
        'her face. The background is a blur of warm summer colors, hinting at a flashback.\n'
        '    - Base Style Settings: artStyles: Romanticism, Impressionism, Fantasy, artMedium - Drawing: '
        'Illustration, Hand-Drawn, artMedium - Paint: Watercolor, artMedium - Text: Calligraphy, Camera - '
        'Scenes: Cinematic, Golden Hour, Filmic, Camera - Film Types: 35mm, Polaroid, Vintage, Camera - Lenses '
        'and Perspective: Wide Angle, Closeup, First-Person view, Camera - Blur and Distortion: Blur Effect, '
        'Camera - Camera Settings: Soft Focus, Shutter Speed 1/1000, Color - Chromatic Palettes: Warm Color '
        'Palette, Light Blue Background, Light, Color - Contrast: High Contrast, Dimensionality - 2D-5D: 2D, '
        '2.5D, Intangibles - Emotions and Qualities: Happy, Nostalgic, Romantic, Lighting - Types: Natural '
        'Lighting, Sunlight, Rays of Shimmering Light, Lighting - Styles: Soft Lighting, Beautiful Lighting, '
        'Material - Opacity: Translucent, Material - Reflection and Refraction: Glossy, Material - Color: '
        'Iridescent\n'
        '    - Elements: close-up of girl, soft nostalgic expression, blurred warm summer colors',
        '- Image 1.3: Generate an image that \n'
        '    - Description: A wide-angle view of a grand balcony overlooking a beautiful summer landscape. The '
        'girl stands on the balcony, her hair flowing gently in the summer breeze, with a serene look on her '
        'face.\n'
        '    - Base Style Settings: artStyles: Romanticism, Impressionism, Fantasy, artMedium - Drawing: '
        'Illustration, Hand-Drawn, artMedium - Paint: Watercolor, artMedium - Text: Calligraphy, Camera - '
        'Scenes: Cinematic, Golden Hour, Filmic, Camera - Film Types: 35mm, Polaroid, Vintage, Camera - Lenses '
        'and Perspective: Wide Angle, Closeup, First-Person view, Camera - Blur and Distortion: Blur Effect, '
        'Camera - Camera Settings: Soft Focus, Shutter Speed 1/1000, Color - Chromatic Palettes: Warm Color '
        'Palette, Light Blue Background, Light, Color - Contrast: High Contrast, Dimensionality - 2D-5D: 2D, '
        '2.5D, Intangibles - Emotions and Qualities: Happy, Nostalgic, Romantic, Lighting - Types: Natural '
        'Lighting, Sunlight, Rays of Shimmering Light, Lighting - Styles: Soft Lighting, Beautiful Lighting, '
        'Material - Opacity: Translucent, Material - Reflection and Refraction: Glossy, Material - Color: '
        'Iridescent\n'
        '    - Elements: grand balcony, beautiful summer landscape, girl with flowing hair, serene look',
        '- Image 1.4: Generate an image that \n'
        '    - Description: A cinematic scene of the girl and boy standing on a balcony together, bathed in the '
        'golden hour light. The summer air is filled with shimmering rays of sunlight, creating a magical and '
        'romantic atmosphere.\n'
        '    - Base Style Settings: artStyles: Romanticism, Impressionism, Fantasy, artMedium - Drawing: '
        'Illustration, Hand-Drawn, artMedium - Paint: Watercolor, artMedium - Text: Calligraphy, Camera - '
        'Scenes: Cinematic, Golden Hour, Filmic, Camera - Film Types: 35mm, Polaroid, Vintage, Camera - Lenses '
        'and Perspective: Wide Angle, Closeup, First-Person view, Camera - Blur and Distortion: Blur Effect, '
        'Camera - Camera Settings: Soft Focus, Shutter Speed 1/1000, Color - Chromatic Palettes: Warm Color '
        'Palette, Light Blue Background, Light, Color - Contrast: High Contrast, Dimensionality - 2D-5D: 2D, '
        '2.5D, Intangibles - Emotions and Qualities: Happy, Nostalgic, Romantic, Lighting - Types: Natural '
        'Lighting, Sunlight, Rays of Shimmering Light, Lighting - Styles: Soft Lighting, Beautiful Lighting, '
        'Material - Opacity: Translucent, Material - Reflection and Refraction: Glossy, Material - Color: '
        'Iridescent\n'
        '    - Elements: girl and boy on balcony, golden hour light, shimmering rays of sunlight, magical atmosphere'
    ],
    [
        '- Image 2.1: Generate an image that \n'
        '    - Description: The scene is a lively party with twinkling lights hanging from trees and a grand '
        'ballroom setting. Elegant guests in ballgowns and suits are mingling, creating a festive and romantic '
        'atmosphere. The background features a large mansion with a beautifully lit garden.\n'
        '    - Base Style Settings: artStyles: Romanticism, Impressionism, Fantasy, artMedium - Drawing: '
        'Illustration, Hand-Drawn, artMedium - Paint: Watercolor, artMedium - Text: Calligraphy, Camera - '
        'Scenes: Cinematic, Golden Hour, Filmic, Camera - Film Types: 35mm, Polaroid, Vintage, Camera - Lenses '
        'and Perspective: Wide Angle, Closeup, First-Person view, Camera - Blur and Distortion: Blur Effect, '
        'Camera - Camera Settings: Soft Focus, Shutter Speed 1/1000, Color - Chromatic Palettes: Warm Color '
        'Palette, Light Blue Background, Light, Color - Contrast: High Contrast, Dimensionality - 2D-5D: 2D, '
        '2.5D, Intangibles - Emotions and Qualities: Happy, Nostalgic, Romantic, Lighting - Types: Natural '
        'Lighting, Sunlight, Rays of Shimmering Light, Lighting - Styles: Soft Lighting, Beautiful Lighting, '
        'Material - Opacity: Translucent, Material - Reflection and Refraction: Glossy, Material - Color: '
        'Iridescent\n'
        '    - Elements: twinkling lights, trees, grand ballroom, guests in ballgowns and suits, mansion, garden',
        '- Image 2.2: Generate an image that \n'
        '    - Description: A close-up view of a young woman in a stunning ballgown, standing under a canopy of '
        'lights. She looks towards the crowd with a hopeful expression, capturing the anticipation of meeting '
        'someone special.\n'
        '    - Base Style Settings: artStyles: Romanticism, Impressionism, Fantasy, artMedium - Drawing: '
        'Illustration, Hand-Drawn, artMedium - Paint: Watercolor, artMedium - Text: Calligraphy, Camera - '
        'Scenes: Cinematic, Golden Hour, Filmic, Camera - Film Types: 35mm, Polaroid, Vintage, Camera - Lenses '
        'and Perspective: Wide Angle, Closeup, First-Person view, Camera - Blur and Distortion: Blur Effect, '
        'Camera - Camera Settings: Soft Focus, Shutter Speed 1/1000, Color - Chromatic Palettes: Warm Color '
        'Palette, Light Blue Background, Light, Color - Contrast: High Contrast, Dimensionality - 2D-5D: 2D, '
        '2.5D, Intangibles - Emotions and Qualities: Happy, Nostalgic, Romantic, Lighting - Types: Natural '
        'Lighting, Sunlight, Rays of Shimmering Light, Lighting - Styles: Soft Lighting, Beautiful Lighting, '
        'Material - Opacity: Translucent, Material - Reflection and Refraction: Glossy, Material - Color: '
        'Iridescent\n'
        '    - Elements: young woman, ballgown, canopy of lights, hopeful expression, crowd',
        '- Image 2.3: Generate an image that \n'
        '    - Description: A wide-angle view of a grand party scene with guests dancing under a sky filled with '
        'stars and hanging fairy lights. The atmosphere is magical, with a mix of warm light and soft shadows '
        'creating an enchanting ambiance.\n'
        '    - Base Style Settings: artStyles: Romanticism, Impressionism, Fantasy, artMedium - Drawing: '
        'Illustration, Hand-Drawn, artMedium - Paint: Watercolor, artMedium - Text: Calligraphy, Camera - '
        'Scenes: Cinematic, Golden Hour, Filmic, Camera - Film Types: 35mm, Polaroid, Vintage, Camera - Lenses '
        'and Perspective: Wide Angle, Closeup, First-Person view, Camera - Blur and Distortion: Blur Effect, '
        'Camera - Camera Settings: Soft Focus, Shutter Speed 1/1000, Color - Chromatic Palettes: Warm Color '
        'Palette, Light Blue Background, Light, Color - Contrast: High Contrast, Dimensionality - 2D-5D: 2D, '
        '2.5D, Intangibles - Emotions and Qualities: Happy, Nostalgic, Romantic, Lighting - Types: Natural '
        'Lighting, Sunlight, Rays of Shimmering Light, Lighting - Styles: Soft Lighting, Beautiful Lighting, '
        'Material - Opacity: Translucent, Material - Reflection and Refraction: Glossy, Material - Color: '
        'Iridescent\n'
        '    - Elements: grand party, dancing guests, stars, fairy lights, magical atmosphere',
        '- Image 2.4: Generate an image that \n'
        '    - Description: A romantic scene where a young man makes his way through a crowd at the party, his '
        'eyes searching for someone. The background features softly lit trees and guests engaged in lively '
        'conversations, adding depth to the scene.\n'
        '    - Base Style Settings: artStyles: Romanticism, Impressionism, Fantasy, artMedium - Drawing: '
        'Illustration, Hand-Drawn, artMedium - Paint: Watercolor, artMedium - Text: Calligraphy, Camera - '
        'Scenes: Cinematic, Golden Hour, Filmic, Camera - Film Types: 35mm, Polaroid, Vintage, Camera - Lenses '
        'and Perspective: Wide Angle, Closeup, First-Person view, Camera - Blur and Distortion: Blur Effect, '
        'Camera - Camera Settings: Soft Focus, Shutter Speed 1/1000, Color - Chromatic Palettes: Warm Color '
        'Palette, Light Blue Background, Light, Color - Contrast: High Contrast, Dimensionality - 2D-5D: 2D, '
        '2.5D, Intangibles - Emotions and Qualities: Happy, Nostalgic, Romantic, Lighting - Types: Natural '
        'Lighting, Sunlight, Rays of Shimmering Light, Lighting - Styles: Soft Lighting, Beautiful Lighting, '
        'Material - Opacity: Translucent, Material - Reflection and Refraction: Glossy, Material - Color: '
        'Iridescent\n'
        '    - Elements: young man, crowd, softly lit trees, lively conversations, searching eyes',
        '- Image 2.5: Generate an image that \n'
        '    - Description: A serene moment where the young man and woman finally meet and say hello amidst the '
        'party. The background is a dreamy blend of warm lights, soft shadows, and elegantly dressed guests, '
        'creating a romantic and nostalgic feel.\n'
        '    - Base Style Settings: artStyles: Romanticism, Impressionism, Fantasy, artMedium - Drawing: '
        'Illustration, Hand-Drawn, artMedium - Paint: Watercolor, artMedium - Text: Calligraphy, Camera - '
        'Scenes: Cinematic, Golden Hour, Filmic, Camera - Film Types: 35mm, Polaroid, Vintage, Camera - Lenses '
        'and Perspective: Wide Angle, Closeup, First-Person view, Camera - Blur and Distortion: Blur Effect, '
        'Camera - Camera Settings: Soft Focus, Shutter Speed 1/1000, Color - Chromatic Palettes: Warm Color '
        'Palette, Light Blue Background, Light, Color - Contrast: High Contrast, Dimensionality - 2D-5D: 2D, '
        '2.5D, Intangibles - Emotions and Qualities: Happy, Nostalgic, Romantic, Lighting - Types: Natural '
        'Lighting, Sunlight, Rays of Shimmering Light, Lighting - Styles: Soft Lighting, Beautiful Lighting, '
        'Material - Opacity: Translucent, Material - Reflection and Refraction: Glossy, Material - Color: '
        'Iridescent\n'
        '    - Elements: young man and woman, saying hello, warm lights, soft shadows, elegantly dressed guests'
    ]
]